// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFMcnE7wqCDWGmyGa963omuswP2iO4YMI',
    appId: '1:159964705152:web:e856a286a177b457319165',
    messagingSenderId: '159964705152',
    projectId: 'commission-shop-86b40',
    authDomain: 'commission-shop-86b40.firebaseapp.com',
    storageBucket: 'commission-shop-86b40.firebasestorage.app',
    measurementId: 'G-TSKNNTJBKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWn1XfbJIf8H-N4VV_3eTNaZDV3u3Yzs',
    appId: '1:159964705152:android:132259569790edef319165',
    messagingSenderId: '159964705152',
    projectId: 'commission-shop-86b40',
    storageBucket: 'commission-shop-86b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRNt9AhWjHRiOX-y4A-bTfsIGnQEqFm0',
    appId: '1:159964705152:ios:2f57f7bfe8c71345319165',
    messagingSenderId: '159964705152',
    projectId: 'commission-shop-86b40',
    storageBucket: 'commission-shop-86b40.firebasestorage.app',
    iosBundleId: 'com.example.comissionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFMcnE7wqCDWGmyGa963omuswP2iO4YMI',
    appId: '1:159964705152:web:b69cb5c4b86711e3319165',
    messagingSenderId: '159964705152',
    projectId: 'commission-shop-86b40',
    authDomain: 'commission-shop-86b40.firebaseapp.com',
    storageBucket: 'commission-shop-86b40.firebasestorage.app',
    measurementId: 'G-ZQP2Z9FS7E',
  );

}